// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Stdlib_Int = require("@rescript/runtime/lib/js/Stdlib_Int.js");
let Stdlib_Option = require("@rescript/runtime/lib/js/Stdlib_Option.js");
let Primitive_option = require("@rescript/runtime/lib/js/Primitive_option.js");

function parse_hex(s) {
  return Stdlib_Int.fromString("0x" + s, 16);
}

function hex2rgb(hex) {
  return Stdlib_Option.map(Stdlib_Option.map(Stdlib_Option.map(Stdlib_Option.map(Primitive_option.fromNullable(new RegExp("^#?([a-f0-9]{2})([a-f0-9]{2})([a-f0-9]{2})$").exec(hex)), prim => prim.slice(1)), a => a.slice(0)), a => a.map(e => Stdlib_Option.flatMap(e, parse_hex))), parsed => {
    if (parsed.length !== 3) {
      return;
    }
    let r = parsed[0];
    if (r === undefined) {
      return;
    }
    let g = parsed[1];
    if (g === undefined) {
      return;
    }
    let b = parsed[2];
    if (b !== undefined) {
      return {
        r: r,
        g: g,
        b: b
      };
    }
  });
}

exports.parse_hex = parse_hex;
exports.hex2rgb = hex2rgb;
/* No side effect */
